export const swaggerDocument = {
  "openapi": "3.0.0",
  "info": {
    "title": "AgentAudit API",
    "description": "API for verifying AI agent reliability using Grounding and Citation checks.",
    "version": "1.0.0",
    "contact": {
      "name": "API Support",
      "email": "support@agent-audit.com"
    }
  },
  "servers": [
    {
      "url": "/api/v1",
      "description": "V1 API"
    }
  ],
  "components": {
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "x-api-key"
      }
    },
    "schemas": {
      "VerifyRequest": {
        "type": "object",
        "required": [
          "question",
          "answer",
          "context"
        ],
        "properties": {
          "question": {
            "type": "string",
            "description": "The original question asked to the AI agent.",
            "example": "What is the capital of France?"
          },
          "answer": {
            "type": "string",
            "description": "The answer generated by the AI agent to be verified.",
            "example": "The capital of France is Paris."
          },
          "context": {
            "type": "string",
            "description": "The source context or documents used to generate the answer. Can be a string or array of strings.",
            "example": "France is a country in Western Europe. Its capital is Paris."
          }
        }
      },
      "VerifyResponse": {
        "type": "object",
        "properties": {
          "trust_score": {
            "type": "number",
            "format": "float",
            "description": "A score between 0 and 1 indicating the reliability of the answer.",
            "example": 0.95
          },
          "action": {
            "type": "string",
            "enum": [
              "APPROVE",
              "REJECT"
            ],
            "description": "Recommended action based on the trust score.",
            "example": "APPROVE"
          },
          "tests": {
            "type": "object",
            "properties": {
              "grounding": {
                "type": "object",
                "properties": {
                  "pass": {
                    "type": "boolean",
                    "example": true
                  },
                  "score": {
                    "type": "number",
                    "example": 1
                  },
                  "reason": {
                    "type": "string",
                    "example": "The answer is directly supported by the provided context."
                  },
                  "unsupported_claims": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "example": []
                  }
                }
              },
              "citation": {
                "type": "object",
                "properties": {
                  "pass": {
                    "type": "boolean",
                    "example": true
                  },
                  "score": {
                    "type": "number",
                    "example": 1
                  },
                  "missing_sources": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "example": []
                  }
                }
              }
            }
          },
          "retry_suggestion": {
            "type": "string",
            "nullable": true,
            "description": "Suggestion for improvement if the verification failed.",
            "example": null
          }
        }
      },
      "StatsResponse": {
        "type": "object",
        "properties": {
          "total_requests": {
            "type": "integer",
            "example": 150
          },
          "average_trust_score": {
            "type": "number",
            "format": "float",
            "example": 0.88
          },
          "hallucination_rate": {
            "type": "string",
            "example": "12.5%"
          }
        }
      },
      "HistoryResponse": {
        "type": "object",
        "properties": {
          "count": {
            "type": "integer",
            "example": 50
          },
          "logs": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "format": "uuid"
                },
                "timestamp": {
                  "type": "string",
                  "format": "date-time"
                },
                "question": {
                  "type": "string"
                },
                "action": {
                  "type": "string",
                  "enum": [
                    "APPROVE",
                    "REJECT",
                    "RETRY"
                  ]
                },
                "trust_score": {
                  "type": "number",
                  "format": "float"
                },
                "latency_ms": {
                  "type": "integer"
                }
              }
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "ApiKeyAuth": []
    }
  ],
  "paths": {
    "/verify": {
      "post": {
        "summary": "Verify AI Content",
        "description": "Analyzes an AI-generated answer against a provided context to determine its accuracy and grounding.",
        "tags": [
          "Verification"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/VerifyRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful verification",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/VerifyResponse"
                }
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "401": {
            "description": "Unauthorized - Invalid API Key"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/stats": {
      "get": {
        "summary": "Get Usage Statistics",
        "description": "Retrieve aggregate statistics about API usage and verification performance.",
        "tags": [
          "Analytics"
        ],
        "responses": {
          "200": {
            "description": "Successful retrieval of stats",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/StatsResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/history": {
      "get": {
        "summary": "Get Verification History",
        "description": "Retrieve the last 50 verification logs for the authenticated API key.",
        "tags": [
          "Analytics"
        ],
        "responses": {
          "200": {
            "description": "Successful retrieval of history",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HistoryResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    }
  }
};
